language: node_js
node_js:
  - 15
services:
  - docker
before_install:
  - docker pull sparksolutionstom/spree-storefront-api-v2-js-sdk:v4.1.0.rc2
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"
script: yarn run test
